#!/usr/bin/env python
# wscript_build
#
# Copyright (c) 2010 Eduardo Niehues
# Distributed under the New BSD License; see LICENSE for details.

source = bld.path.ant_glob('*.vala')
flags = ['-g']

if bld.env['windows'] == 'yes':
	flags.extend(['-mms-bitfields', '-mwindows'])

bld.program(
	source = bld.path.ant_glob('*.vala'),
	features  = 'c cprogram',
	packages  = 'gio-2.0 gee-0.8 posix glib-2.0 libsoup-2.4 libxml-2.0 sqlite3',
	vapi_dirs = '../vapi',
	includes  = '../vapi',
	target    = 'xsrss',
	cflags    = ['-include','config.h','-g'],
	linkflags = flags,
	uselib    = 'GLIB GIO GEE SOUP SQLITE XML',
)
